gnuboard/g6

admin/admin_board.py
bbs/board.py

- form validation 오류 수정
- 게시판 복사시 파일 첨부 되도록 수정

fix: 게시판 복사 기능

---

bbs/social.py
core/models.py

fix: 소셜 로그인 테이블 컬럼 mp_id -> mp_no

---

bbs/memo.py

po_rel_action -> 포인트 소진 사유 받도록 수정

[fix] #276 쪽지전송 오류 수정

---

bbs/social.py

get_profile_by_member_id -> get_profile_by_identifer 변경
중복 위험이 있는 컨버터 id대신 제공되는 고유값 idenfiter 로 수정
그누보드 5 데이터 insert 시 불일치 수정

fix: 소셜 로그인 identifier 값 수정

---

core/middleware.py

- `HTTPSRedirectMiddleware` 미들웨어에서 **모든 요청을 HTTPS로 변경**하기 때문에 발생한 오류
- #64
- #305
- **`X-Forwarded-Proto` 헤더**를 통해 클라이언트에서 **실제로 사용할 scheme을 설정**하도록 변경
- starlette > `HTTPSRedirectMiddleware` 이름 중복으로 인한 클래스 이름 수정
- `HTTPSRedirectMiddleware` -> `BaseSchemeMiddleware`

fix: https 미들웨어 오류 수정

---

bbs/board.py

- 비로그인 유저 게시글 읽기 포인트 차감 검증시 None object chain method 오류 수정
- 글 작성자는 비밀 댓글 읽기 가능하도록 수정

fix: 게시글 읽기 관련 오류 수정

---

core/template.py

- core > template.py > TemplateResponse 함수 인자 => 키워드 인자 추가 수정
- #309 
- #249

fix: TemplateResponse 인자 오류 추가 수정

---

bbs/board.py

댓글이 검색 필터에 잡힌 경우, 더 보기 이동시, 댓글이 포함된
원 게시글(부모글)을 더보기 시에 나오도록 수정

fix: #301 댓글 검색시 더보기 기능 보완

---

bbs/memo.py
core/models.py
lib/common.py
templates/basic/memo/memo_list.html
templates/taeho/memo/memo_list.html

- #128 
- 그누보드5 DB와 호환성을 가지도록 `NotNull=False` 변경
- 기본값 변경 
-  `datetime(1, 1, 1, 0, 0, 0)`
- #26 참고
- 관련된 코드 수정 (`is_none_datetime` 함수)
- 
- 쪽지 목록이 없을 경우 "쪽지가 없습니다." 메시지 출력

fix: 그누보드5 쪽지 테이블 호환 문제 수정

---

bbs/current_connect.py
lib/common.py

- 기본환경설정 > 현재 접속자 설정에 대한 where절 조건이 누락되어서 추가함.
- 접속자 목록, 접속자 수 출력에서 `lo_datetime` 컬럼 조건 추가
- #320

fix: 현재 접속자 > 기본환경설정이 적용되지 않는 오류 수정

---

static/plugin/editor/ckeditor4/config.js
static/plugin/editor/ckeditor4/darkmode.css
static/plugin/editor/ckeditor4/skins/office2013/editor.css

- [x ] 테스트가 성공적으로 수행되었는지 확인했습니다.
- [x ] 버그 수정
- [x ] 새로운 기능

[fix] #291 에디터영역 다크모드 기능 적용

---

admin/templates/basic/board_list.html
admin/templates/basic/boardgroup_list.html
admin/templates/basic/member_form.html
admin/templates/basic/plugin_list.html
admin/templates/basic/visit_delete.html
templates/taeho/mobile/bbs/outlogin_after.html
templates/taeho/static/css/outlogin.css

- 스크랩 갯수를 표시하는 태그 누락
- 좌측메뉴와 동일하게 수정
- #297 
- #298 
@seiblog-nandsoft 제안

fix: 모바일&관리자페이지 HTML 태그 관련 오류 수정

---

bbs/board.py

게시글에 파일 첨부후 게시글 조회시, 첨부파일에 이미지가 아닌 파일들만 나왔으나
이미지도 첨부파일 목록에 나오도록 변경하였습니다.
#224

add: 게시판 첨부파일 > 이미지도 첨부파일 목록에 표시

---

templates/taeho/latest/main_list.html

메인페이지에서 최신 공지글 슬라이드에서 제목 클릭시 해당 글로 이동할 수 있도록 했습니다.
#231

fix: 최신 공지글 링크 작동하도록 수정

---

admin/templates/basic/plugin_menu_header.html
core/middleware.py
core/plugin.py
core/template.py
main.py
plugin/demo_plugin/admin/admin_router.py
plugin/demo_plugin/plugin_config.py
plugin/demo_plugin/user/user_router.py
plugin/demo_todo/admin/admin_router.py
plugin/demo_todo/plugin_config.py
plugin/demo_todo/user/user_router.py

그누보드 템플릿 클래스 사용
UserTemplate 에 플러그인 폴더 등록
plugin_config 의 TEMPLATE_PATH 를 사용
- [V] 버그 수정
[https://github.com/gnuboard/g6/issues/334](https://github.com/gnuboard/g6/issues/334)

[fix] #334 플러그인 경로 수정

---

plugin/demo_todo/admin/admin_router.py

- [x ] 테스트가 성공적으로 수행되었는지 확인했습니다.
- [ x] 버그 수정

경로에 / 누락으로 추가함

---

bbs/member_profile.py

- Redirect URL 오류 수정
```
url_path_for에 해당하는 member_confirm 함수나, name이 설정된 곳이 없습니다.
해당 if문을 고려하여 member_password로 name이 설정된 check_member함수로 redirect 해주도록 변경했습니다.
```
- 순환참조 오류 수정
```
main.app이 아닌 request를 이용해서 순환참조가 없도록 변경했습니다.
```

fix: 회원정보 수정 > Redirect URL, 순환참조 오류 수정

---

admin/admin_board.py

1. 동적모델 캐시 삭제처리 추가 `_created_models`
2. 게시판 테이블의 인덱스 삭제처리 추가
- 트랜잭션으로 인한 database locked 발생 -> `db.commit()` 처리 시점 조정
[sir.kr > 게시판 삭제가 안되는데 혹시 다른분도 그러신가요?](https://sir.kr/qa/523236)

fix: 관리자페이지 > 게시판 삭제 오류 수정

---

bbs/social.py

[fix] Update social.py

---

core/database.py

'DBConnect' 클래스의 해결되지 않은 속성 참조 '_instance'
싱글턴 클래스 _instance 변수 부재로 인한 경고
attr로 해당 변수(_instance)이 있는지 확인하는 것보단 default value를 null로 정의 후 사용하는 것이 조금 더 보편적인 방법이라 제안드립니다.
(IDE 경고 또한 제거 가능)

IDE 경고 : 'DBConnect' 클래스의 해결되지 않은 속성 참조 '_instance'

---

core/database.py

- `DB_PORT` 값이 항상 `int`형으로 되도록 수정
- `env_values.get()` 는 문자열을 리턴한다
- https://github.com/gnuboard/g6/pull/346

fix: database.py > _port 변수가 항상 int형을 가질 수 있도록 수정

---

core/database.py

타입 'int'이(가) 필요하나 대신 'str | None'을(를) 얻었습니다
Default value 0 추가
Default value 0 추가

IDE 경고 : 타입 'int'이(가) 필요하나 대신 'str | None'을(를) 얻었습니다

---

bbs/board.py

기존 이슈 내용대로, 댓글에 HTML 태그를 프록시 도구 / 리퀘스트 프로그램을 통해 작성 가능하였습니다. 이를 렌더링 할 때 HTML Escaping 처리를 하여 해당 문제를 해결하였습니다.
#316

fix: 댓글 작성 시 HTML Escaping 처리 (#316)

---

bbs/board.py
bbs/poll.py
bbs/qa.py
templates/basic/bbs/poll_result.html

- #347 와 동일한 내용을 **게시글/Q&A/투표 기타의견**에도 추가 적용
- poll 변수가 Template Context에서 중복 선언되지 않도록 변수명 변경
- #314 
- #316

fix:  HTML Escaping 추가 처리, 투표 오류 수정

---

bbs/board.py
bbs/qa.py

- 모든 HTML 태그를 제거하기 때문에 script태그만 변환될 수 있도록 다른 방법이 필요
- ex) 이미지 태그
- #314

fix: #314 게시글/Q&A 내용 작성 시 HTML Escaping 처리 원복

---

plugin/demo_plugin/plugin_config.py
plugin/demo_todo/plugin_config.py

플러그인의 라우터 접두사를 사용하지 않을경우 "" 빈문자열로 설정이라는 주석 추가

[docs] 플러그인 라우터 주석 추가

---

templates/basic/base.html
templates/basic/bbs/menu.html

- 병합충돌 및 코드 추가수정으로 인해 새로운 PR을 만들어 반영합니다.
- #352 
@seiblog-nandsoft 님 제안

fix: #352 메뉴가 없을때 border 표현 되던 오류 수정

---

templates/basic/static/css/default.css

[fix].  default.css 중복코드 제거

---

core/database.py
core/models.py
example.env
lib/common.py

- 설치시, MySQL에서 데이터베이스 charset에 따라 테이블이 생성되지 않는 오류 수정
- .env 파일에 `DB_CHARSET` 활용(utf8mb4)

fix: MySQL 데이터베이스 설치 오류 수정

---

bbs/social.py
lib/member_lib.py
templates/basic/social/social_register_member.html

소셜로그인 가입시 소셜사이트에서 제공되는닉네임, 이메일 자동기입, 
member_social_profiles 테이블 displayname  입력 수정
소셜 로그인 템플릿 exist_email 체크 누락 추가
social_user_nick -> form.social_nickname 템플릿 변수 변경
social_member_email - 없는 변수 -> form.social_email  
네이버 아이디 로그인에서 닉네임, E-mail 을 자동 입력하지 않는 오류
https://github.com/gnuboard/g6/issues/367

fix: 소셜로그인가입시 닉네임, 이메일 입력 수정

---

core/middleware.py
example.env
install/router.py

fix: 세션키 설정

---

admin/admin_visit.py
lib/common.py

- 접속자 삭제, 접속자집계 페이지에서 MySQL, PostgreSQL > concat 문법오류 수정
- SQLite는 concat 함수 자체가 없으므로 컬럼에서 지원하는 concat 적용
- #362
- #369

fix: 접속자이력이 삭제되는 오류 수정

---

bbs/board.py
core/middleware.py
lib/dependencies.py
lib/template_filters.py
main.py
templates/basic/board/basic/write_form.html
templates/basic/board/gallery/write_form.html

- 그누보드5의 데이터베이스를 그대로 사용하는 경우 발생
- 그누보드는 **ip가 기본키**로 설정되어 있어, 기본 키 입력 오류가 발생하고 이 과정 중에 **DBSession이 close**되지 않음.
- 오류가 발생해도 DBSession이 종료되도록 수정
- query_string > parent_id 중복으로 인한 오류 수정
- 취소버튼에서 parent_id 제거

fix: middleware에서 현재 접속자 처리 오류 수정 외 4건 

---

admin/templates/basic/base.html

그누보드 5에서 사용하지 않는 함수
함수 내부의 selectBoxVisible, selectBoxHidden 는 그누보드 5부터 존재 하지않음 
그누보드 4에서 IE 표시 문제를 해결하는데 사용하던 함수.

remove: 불필요한 js imageview 함수 삭제

---

lib/board_lib.py

아래 PR에서 다른 작업내용의 commit이 함께 있어 별도의 PR 생성 후 반영
- #339

fix: 최근 게시물 제목 길이 제한이 누락된 부분 수정

---

admin/admin_member.py
admin/templates/basic/member_form.html
admin/templates/basic/sideview/macros.html
bbs/member_profile.py
bbs/register.py
core/middleware.py
lib/common.py
lib/member_lib.py
templates/basic/base.html
templates/basic/bbs/current_connect.html
templates/basic/bbs/outlogin_after.html
templates/basic/board/basic/read_post.html
templates/basic/board/gallery/read_post.html
templates/basic/member/member_profile.html
templates/basic/memo/memo_list.html
templates/basic/memo/memo_view.html
templates/basic/mobile/bbs/outlogin_after.html
templates/basic/sideview/macros.html

회원 이미지, 아이콘 업로드 관련하여 아래의 내용이 포함되어 있습니다.
```
유효성 검사 수정
- 가능한 이미지 파일 확장자 추가 (DB의 설정 값을 사용하도록 수정)
- 이미지 파일에 대한 사이즈 검증 추가(DB의 설정 값을 사용하도록 수정 - 기존은 아이콘만 검증)
유효성 검사 및 업로드 > 같은 기능을 하는 부분들 공통 함수로 리팩토링
관리자 페이지에서 회원 이미지 삭제시 회원 아이콘이 삭제되는 오류 수정
```
#385

fix. 회원 이미지, 아이콘 유효성 검사, 업로드 기능 수정

---

static/admin/admin.js
static/js/common.js
static/js/wrest.js
templates/basic/social/social_register_member.html

호출 되지 않고 사용불가한 코드 삭제 
common.js 
- doc_write(), 플래시 함수, php 토큰 발급함수
admin.js
-  btn_check() 그누보드 4 에서 사용하는 함수 (5 부터 실행안함)
소셜로그인 템플릿 php 주석 삭제

remove: 불필요한 js 함수, 코드 삭제

---

main.py

- lo_id 고정값 삭제
lo_id = 25 고정 값으로 처리되는 오류 수정

fix: middleware > 현재접속자 정보 입력 오류 수정

---

admin/admin_poll.py

#392 
Poll field null 값 대입이 불가함(default"")
null 값 default value로 변경

Poll 수정 시 오류 500 error

---

admin/admin_poll.py

- 수정일 경우에도 캐시 갱신되도록 처리
- fully NULL primary key identity cannot load any object. 경고 문구 해결
- #392

fix: 설문조사 수정 시, 캐시 갱신 및 오류 수정

---

plugin/demo_todo/admin/__init__.py
plugin/demo_todo/models.py

테이블 체크 삭제, 테이블생성 함수 플러그인 models.py 로 이동
플러그인은 서버실행이후 첫번째로 등록될 때 플러그인내 모든 파일을 import 하게 됩니다. 
이때 실행되어 테이블이 생성됩니다.
* 관리자에서 사용안함 -> 사용을 눌러도 이미 파이썬 파일들이 import 되었기 때문에 두번이상 실행되지는 않습니다.
* 이미 테이블이 존재하는경우 생성은 건너뛰게 되어있습니다.

refact: 플러그인 테이블 생성 수정

---

admin/admin_visit.py
admin/templates/basic/visit_forms.html
admin/templates/basic/visit_list.html

1) 관리자 > 접속자 전체 집계 출력되도록 추가
2) 관리자 > 접속자 도메인 별 집계에서 도메인 직접 접속시 request headers의 referer 값이 None으로 넘어오는 경우가
코드 상에서 누락되어 있어서 수정하였습니다.
(DB 상에 None으로 넘어오는 경우 데이터를 저장하는데, 출력상에서 해당하는 경우를 고려하지 않고 있었음)
#410

관리자 > 접속자 집계 도메인 오류 수정 및 기능 추가

---

README.md

README.md 
- 커뮤니티 추가 [https://sir.kr/main/g6](https://sir.kr/main/g6)
- 유튜브 채널 추가 [https://www.youtube.com/@gnuboard-official](https://www.youtube.com/@gnuboard-official)

docs: README.md > 커뮤니티 항목 추가

---

admin/templates/basic/visit_domain.html

관리자 페이지 내의 접속자 집계 - 도메인 탭에서 도메인이 왼쪽 정렬 되도록 수정했습니다.

[style] 관리자 > 접속자 집계 - 도메인: 왼쪽 정렬 적용

---

admin/admin_config.py
admin/templates/basic/config_form.html
lib/common.py

관리자 기본 환경설정에서 관리자 접속 클라이언트 IP와 서버의 IP(사설+공인)를 볼 수 있도록 했습니다.
#412

add. 관리자 > 관리자 및 서버 IP 주소 조회

---

static/js/common.js

자바스크립트 check_field  함수 동작 오류 
trim 함수

fix: js check_field 함수 오류 수정

---

lib/common.py

캐시값 비어있는 배열도 계속 쿼리가 실행됨
-> 캐시 초기화 조건인 None 일 때 만 DB 실행
get_menus db.close() 추가
캐시 none 이 캐시 삭제조건인데, 유비콘 실행 옵션으로 work 를 여러개 켰을 경우 캐시를 삭제 할 수 없습니다.

refact: user 템플릿 공통 context 함수들 캐시 조건 개선

---

lib/social/social.py
templates/basic/bbs/outlogin_after.html
templates/basic/social/social_register_member.html

* 회원탈퇴 링크수정
* 소셜 가입시 is_regisrter  불필요한 체크 삭제
* is_register 로 인해 가입시 정보 수정으로 나오는 문제 수정

fix: 소셜 가입시 체크, 회원 탈퇴 수정

---

bbs/member_profile.py
templates/basic/board/basic/list_post.html
templates/basic/board/basic/read_post.html
templates/basic/board/gallery/read_post.html
templates/basic/memo/memo_form.html
templates/basic/memo/memo_list.html
templates/basic/qa/qa_list.html
templates/basic/qa/qa_view.html

1. 회원정보 수정 완료 시, 안내문구 출력 추가
2. 쪽지 > 텍스트 수정
3. 게시판 목록 > 제목길이 제한 기능누락 수정 (basic skin)
4. SQLite에서 게시판, Q&A 날짜표기 오류 수정
- #431 
- #432 
- #439 
- #445

fix: 이슈 > 오류&수정사항 4건 처리

---

core/database.py
example.env

DB 연결시 비밀번호에 특수문자 오류수정
- 문자열 url 연결  -> sqlalchemy URL 객체로 연결로 수정
PostgreSQL 인코딩 옵션 추가
https://docs.sqlalchemy.org/en/20/dialects/postgresql.html#psycopg2-unicode
* env 에서 DB_CHARSET 값을 
mysql 은 utf8mb4  (현재 기본값)
PostgreSQL 은 utf8   로 변경해야합니다.

fix: DB 연결시 특수문자 입력수정

---

admin/admin_boardgroup.py
admin/admin_cache.py
admin/admin_mail.py
admin/admin_menu_bbs.json
admin/admin_plugin.py
admin/templates/basic/mail_select_result.html
lib/template_filters.py

- Mysql에서 `0000-00-00 00:00:00` 형식의 날짜를 처리하지 못하는 문제 수정
- `admin_menu_bbs.json` 파일
- `AlertException` => `EventSourceResponse`
- #445

fix: 오류&수정사항 4건 처리

---

static/admin/admin.css

- 관리자 모드 font-size 단위를 em, px 에서 rem 으로 변경했습니다.
- 반응형 font-size 크기를 1.2rem (데스크탑) 1.4rem (모바일)으로 변경했습니다.
#416

[refactor] 관리자 font-size 단위 및 크기 변경

---

core/middleware.py

FastAPI에서 기본 제공하는 swagger(/docs)를 이용하기 위한 허용 URL 추가

[fix] Content-Secutiry-Policy 허용 url 추가

---

install/router.py

초기 설치 시, DBSetting 클래스가 싱글턴으로 인해 **데이터베이스 정보를 갱신하지 못해** 데이터베이스 테이블이 정상적으로 설치되지 않음
설치 진행 시 데이터베이스 설정 클래스 내부의 변수들을 갱신하도록 함수 실행 추가
- #458

fix: 설치시 데이터베이스 오류 수정

---

bbs/board.py
bbs/password.py
lib/board_lib.py

fix: 게시글 관련 오류사항 3건 수정

---

templates/basic/mobile/static/css/board_common.css
templates/basic/mobile/static/css/board_skin_basic.css
templates/basic/mobile/static/css/default.css
templates/basic/qa/qa_form.html
templates/basic/qa/qa_list.html
templates/basic/qa/qa_view.html
templates/basic/static/css/board_common.css
templates/basic/static/css/default.css
templates/basic/static/css/qa.css

- QA(1:1문의)에 스타일시트를 연결했습니다. (누락분 수정)
- 게시판 이전글 다음글에서 글제목이 길 경우 레이아웃이 깨지는 현상을 수정했습니다. (게시판 목록 포함)
#477

[fix/style] QA 스타일시트 연결 및 게시판 이전글 다음글 스타일 조정

---

core/middleware.py

프로젝트 내에서 호출해야하는 외부 url과 ckeditor 사용성을 위해 data: 를 Content-Security-Policy 항목에 추가합니다.
#471

[fix] #471 Content-Security-Policy 허용 src 추가

---

admin/admin_member.py
admin/templates/basic/base.html
admin/templates/basic/index.html
admin/templates/basic/member_form.html
bbs/profile.py
main.py

- main.py import 순서 변경
-  5건 고정 표시 -> 목록에 표시된 건수로 변경
- #396 
- #402 
- #465

fix: 오류 및 수정사항 4건 적용

---

admin/admin_auth.py
bbs/register.py
templates/basic/board/basic/read_post.html
templates/basic/board/gallery/read_post.html
templates/basic/mobile/board/basic/read_post.html
templates/basic/mobile/board/gallery/read_post.html
templates/basic/qa/qa_view.html

- 3~20자 제한
- 영문자, 숫자, _ 만 입력 가능
- 업로드된 파일의 원본 이미지 경로로 이동
- #397 
- #436
- #481 
close #397 
close #481

fix: 오류 및 개선사항 3건 수정

---

admin/admin_visit.py

브랜치 정리, 
* OS: 17년전 os 일부삭제   IOS 추가
* 봇 분류 추가
* 브라우저 : 넷스케이프, 게코 삭제, 사파리 추가

방문자 내역 봇, ios 추가

---

core/database.py
lib/board_lib.py
lib/member_lib.py

sql알케미관련 임포트 오류 수정
member_lib > update_member_image 함수
delete 매개변수 형변환 수정 1 -> True

fix: 임포트, 타입에러 수정

---

admin/admin_cache.py
core/database.py
install/router.py

- yield 및 Except를 사용한 종속성에서 raise를 통해 예외를 발생시키도록 수정 (메모리 누수 수정)
- https://github.com/tiangolo/fastapi/releases/tag/0.110.0
- 비동기 함수에서는 `AsyncGenerator`를 반환
- `Session` -> `AsyncGenerator[AsyncSession, None]`

perf/fix: fastapi 0.110 버전 변경사항 대응 외 1건

---

core/middleware.py

사용자 편의성을 고려하여 Content-Security-Policy 미들웨어를 제거합니다
사용자 편의성을 위해 Content-Security-Policy 미들웨어를 제거합니다.

[fix] Content-Security-Policy middleware 제거

---

example.env
lib/scheduler/__init__.py
lib/scheduler/scheduled_jobs/__init__.py
lib/scheduler/scheduled_jobs/cron_schedules.py
lib/scheduler/scheduled_jobs/date_schedules.py
lib/scheduler/scheduled_jobs/interval_schedules.py
lib/scheduler/scheduler.py
main.py

스케줄러 기능 추가 및 모듈화
- 기존 cron + interval, date 기능 추가 및 모듈화

[add] 스케줄러 모듈화 및 기능 추가

---

api/v1/auth/jwt.py
api/v1/routers/auth.py

[refact] JWT 생성 메소드 > token type에 따라 분기

---

lib/scheduler/scheduler.py

- class Scheduler 내에서 변수에 대한 접근과 사용 메소드를 용도에 맞게 변경

[refact] Scheduler > class 내의 메소드 및 변수 접근 방법 변경

---

admin/admin_mail.py
admin/admin_sendmail.py
admin/templates/basic/config_form.html
admin/templates/basic/sendmail_test.html
bbs/formmail.py
bbs/member_find.py
bbs/poll.py
bbs/qa.py
bbs/register.py
bbs/social.py
lib/board_lib.py
lib/common.py

1. 보내는 이메일 (`from_email`)을 첫번째에 파라미터 추가
2. port(465, 587)에 따른 SMTP 서버 설정 분리
```
if SMTP_PORT == 465:
server = smtplib.SMTP_SSL(SMTP_SERVER, SMTP_PORT, timeout=10)
else: # port: 587
server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT, timeout=10)
server.starttls()
```
3. 메일발송 실패 시, 예외처리 세분화
- NoneType 오류 방지 
- 최고관리자 메일 조회
- #494 
- [메일 전송 질문](https://sir.kr/qa/527630#answer_527640)
메일 전송 및 템플릿은 추후에도 개선이 필요함.

fix: 메일 전송 코드 개선 및 오류 수정

---

README.md
admin/admin_plugin.py
admin/admin_theme.py
core/plugin.py
core/template.py

테마, 플러그인 이미지에 webp 보기 추가 screenshot.webp
webp 파일을 먼저 찾고 png 를 찾게 변경합니다.
버그 수정
core/template.py 에서 screenshot 이미지 파일이 없을 때 테마가 목록에 등록되지 않는 문제수정

feat: 테마,플러그인 이미지 webp 보기 추가

---

admin/admin_mail.py
admin/admin_sendmail.py
bbs/formmail.py
bbs/member_find.py
bbs/poll.py
bbs/qa.py
bbs/register.py
bbs/social.py
lib/board_lib.py
lib/common.py

- `mailer()` 함수 > `from_name`, `to_name` 매개변수 추가
- `get_admin_email_name()` 함수 추가
- 관리자페이지 > 회원메일 발송 오류 시 예외처리 추가
[메일 발송 제목 문제](https://sir.kr/qa/527733)

fix: 메일 > 보내는 사람 추가 및 오류 수정 

---

lib/html_sanitizer/allowed_dict.py

- 글 내용 저장 시, 'strong', 's' 태그가 허용되도록 추가
- `content_private_allowed_tags_dict` 변수 > `text` 속성 > 알파벳 순 정렬 
- #502

[fix] #502 글 작성 시, 에디터의 볼드체, 취소선이 적용되지 않는 문제 수정

---

templates/basic/board/basic/write_form.html
templates/basic/board/gallery/write_form.html
templates/basic/mobile/board/basic/write_form.html
templates/basic/mobile/board/gallery/write_form.html
templates/basic/mobile/static/css/board_common.css
templates/basic/mobile/static/css/default.css
templates/basic/static/css/board_common.css
templates/basic/static/css/default.css

- 게시물 수정 시 첨부파일 삭제 UI 깨지는 현상을 수정했습니다.
- 게시물 작성/수정 시 첨부파일 선택자 오타를 수정했습니다.
- 적응형 모바일 버전에서 배경화면 색상을 재지정했습니다.
#507

[fix/style] #507 게시물 수정 시 첨부파일 삭제 UI 깨지는 현상 수정(선택자 오타 수정), 적응형 모바일 배경화면 재지정

---

api/v1/models/board.py
api/v1/routers/board.py

- api response 형태 제공
- model에 정의된 속성만 필터링

[add] 게시판 REST API > response model 추가

---

bbs/memo.py
templates/basic/memo/memo_view.html
templates/bootstrap/memo/memo_view.html

- 쪽지 발송 시 `html sanitizer` 추가 적용
- 쪽지 내용 출력 시 `safe` 필터 제거

fix: 쪽지 > 쪽지 발송 시 Store XSS 방지 기능 추가

---

lib/scheduler/scheduler.py

스케쥴러 중복 등록 방지용으로 임시 작성하는 파일 내용을 한글 대신 영어로 변경
#512

[fix] #512 Scheduler > 인코딩 오류 수정

---

static/admin/admin.css
static/js/common.js
templates/basic/base.html
templates/basic/mobile/base.html
templates/basic/mobile/static/css/default.css
templates/basic/static/css/default.css
templates/bootstrap/mobile/base.html
templates/bootstrap/mobile/static/css/default.css

다크모드 버튼 태그 속성 중 `class`가 `id`로 변경하면서 같이 변경되어야 하는 부분이 누락되어 생긴 오류
- 변경 누락된 부분 수정 (class -> id)
- 현재 다크모드일 경우, 버튼을 두번 눌러야 작동하는 오류 수정
[라이트모드 다크모드 변경토글이 안되는거 같아요.](https://sir.kr/qa/529740)

fix: 다크모드 버튼 오류 수정

---

service/board/update_post.py

리팩토링 과정에서 잘못 쓰여진 부분 수정
- 잘못된 변수 선언 변경(tuple -> str)
- 함수 인자 변경

[fix] 잘못된 부분 제거 및 인자 변경(sql)

---

requirements.txt

- cryptography 41.0.7 -> 42.0.4
- idna 3.4 -> 3.7
- Jinja2 3.1.2 -> 3.1.4
- python-multipart 0.6 -> 0.9

fix: 패키지 취약점 버전 업데이트

---

admin/templates/basic/index.html
admin/templates/basic/member_list.html
admin/templates/basic/point_list.html
admin/templates/basic/sideview/macros.html
bbs/formmail.py
core/routers.py
core/template.py
templates/basic/sideview/macros.html
templates/bootstrap/sideview/macros.html

사이드뷰를 통해 타 유저에게 이메일 발송
- 라우터 함수 누락된 부분 수정
- 프론트단 이메일 암호화 로직 누락된 부분 수정
- 관리자 페이지 멤버 email, homepage 속성 수정

[fix] 사이드뷰 메일 발송 관련 오류 수정

---

plugin/demo_plugin/user/__init__.py
plugin/demo_todo/user/__init__.py

- 사용자페이지(템플릿)에 필요한 데이터 (template_data) 추가

fix: 플러그인 > 사용자페이지 접근시 오류 수정

---

bbs/login.py
main.py

starlette 라이브러리에서 사용하는 class Response 내에 set_cookie, delete_cookie 메소드는
async가 붙지 않는 동기함수이므로 await를 붙여서 코드를 작성한 부분을 수정하였습니다.

[fix] 동기함수에 잘못 사용된 await 제거 (starlette)

---

api/v1/dependencies/qa.py
api/v1/routers/qa.py
bbs/qa.py
lib/dependency/qa.py
service/qa_service.py
templates/basic/qa/qa_view.html
templates/bootstrap/qa/qa_view.html

- 업로드 된 파일 경로를 직접적으로 알 수 없도록 파일 다운로드 Router 추가
- 업로드 파일 확장자 검사 추가 및 유효성 검사 의존성 함수 적용
- REST API > Q&A 파일 다운로드 추가

fix: Q&A 파일 업로드 취약점(KVE-2024-0225) 외 오류 1건 수정

---

admin/admin_theme.py

- static 경로가 캐시로 인해 제대로 설정되지 않아서 발생
- 테마관련 캐시를 삭제하는 코드 위치 변경
- 메인페이지 > 최신글 캐시 삭제 로직 추가

[fix] 테마 변경 시 화면 깨짐 오류 수정

---

templates/bootstrap/qa/qa_view.html

fix: 부트스트랩 테마 > Q&A 상세페이지 오류 수정

---

api/v1/models/board.py
api/v1/routers/board.py
api/v1/service/board.py
core/exception.py
service/board/board.py
service/board/list_post.py
service/board/read_post.py

- 글 조회시 속성 추가
```
첨부파일, 작성자 아이콘, 이미지
```
- 비밀글 접근 오류 수정
```
REST API: 회원 작성 비밀글이 검증이 안되던 로직 수정
Template: 작성자나 관리자가 아닌 제3자가 비밀글 접근시 비밀번호 입력페이지로 이동하도록 수정
```
- 미사용 라이브러리 호출 제거
비밀글 접근 오류 수정 - #535

[fix] REST API 게시판 정보 조회 속성 추가 / 비밀글 접근 오류 수정

---

admin/admin_config.py
bbs/index.py
bbs/login.py
bbs/member_profile.py
bbs/memo.py
bbs/password.py
bbs/register.py
bbs/social.py
core/models.py
core/routers.py
lib/dependency/dependencies.py
lib/template_filters.py
main.py
templates/basic/member/register_form.html
templates/basic/memo/memo_list.html
templates/basic/social/social_register_member.html
templates/bootstrap/member/register_form.html
templates/bootstrap/memo/memo_list.html
templates/bootstrap/social/social_register_member.html

- 사용자페이지에 접근할 때만 동작하도록 개선
- 현재 접속자 카운트가 맞지 않는 오류 수정
- 캐시가 정상적으로 갱신되도록 처리
- Jinja2 Template `default` 필터의 2번째 매개변수로 처리 가능
- https://jinja.palletsprojects.com/en/3.1.x/templates/#jinja-filters.default
- #530

fix: 현재접속자 카운트 오류 및 개선사항 반영

---

api/v1/auth/jwt.py
api/v1/dependencies/auth.py
api/v1/routers/auth.py
requirements.txt

- 첫 JWT 발급 시, 기존 리프레시 토큰 정보를 삭제하도록 코드 추가
- 보안 이슈로 인해 python-jose -> PyJWT 변경
- #534 
- https://github.com/gnuboard/g6/security/dependabot/8
- https://github.com/gnuboard/g6/security/dependabot/9

fix: REST API > JWT 오류 및 수정사항 반영

---

api/v1/routers/board.py

REST API 글쓰기시 권한 검증 후, 권한 미달시 에러를 반환하는 메소드로 변경
#544

[fix] #544 REST API > 게시판 글쓰기 권한 검증 로직 수정

---

api/v1/dependencies/scrap.py
api/v1/routers/board_new.py
bbs/board_new.py
lib/dependency/scrap.py
service/scrap_service.py
templates/basic/mobile/static/css/default.css
templates/basic/new/basic/new_list.html
templates/basic/static/css/default.css
templates/bootstrap/bbs/password.html
templates/bootstrap/bbs/scrap_list.html
templates/bootstrap/new/basic/new_list.html

- 권한 체크가 제대로 적용되지 않은 문제점 수정
- 스크랩 목록 페이지 > 게시글 제목
- 비밀글 확인 페이지 > 게시글 제목
- #545 
- #548

fix: KVE-2024-0223 취약점 외 수정사항 2건 적용

---

admin/templates/basic/board_form.html
api/v1/models/board.py
api/v1/models/config.py
api/v1/routers/board.py
api/v1/routers/board_new.py
api/v1/routers/config.py
bbs/search.py
lib/board_lib.py
main.py
service/ajax/ajax.py
service/board/list_post.py
service/board_new/board_new.py
service/popular_service.py
service/search/search.py
templates/basic/bbs/search.html

- REST API에서 게시글 조회시 좋아요/싫어요 (good/nogood) 정보 추가
- 게시판 설정 정보 조회 REST API 추가
- 최신 게시물 정보 조회 API 추가 (table 종합, 개별 table)
- 관리자 게시판 검색 사용 여부 하드코딩 오류 수정
- 인기 검색어 조회 캐싱 방법 변경(LRU -> TTL)
- 게시판 검색 미비 사항 추가 (템플릿 수정 / 예외 처리 수정)
#538 
#539
#560
#562
#563
#564

[add, fix] 게시글 관련 이슈사항 기능 추가 및 오류 수정

---

api/v1/dependencies/scrap.py
api/v1/routers/memo.py
api/v1/routers/qa.py
api/v1/routers/scrap.py
bbs/memo.py
bbs/qa.py
bbs/scrap.py
core/models.py
lib/dependency/scrap.py
service/memo_service.py
service/scrap_service.py
templates/basic/bbs/poll_result.html
templates/basic/bbs/scrap_list.html
templates/basic/memo/memo_list.html
templates/bootstrap/bbs/point_list.html
templates/bootstrap/bbs/poll_result.html
templates/bootstrap/bbs/scrap_list.html
templates/bootstrap/memo/memo_form.html
templates/bootstrap/memo/memo_list.html

- 일부 데이터의 등록시간이 고정으로 입력되는 문제 수정
- 설문조사, 스크랩, 포인트, 쪽지 페이지 오류 및 서식 수정
- 쪽지 전송 시 포인트 차감이 되지 않는 오류 수정
- 답변 글에서 업로드된 파일이 보이지 않는 오류 수정
- 댓글은 스크랩되지 않도록 유효성 검사 추가
- 비밀글이 아닌 경우에도 비밀글 권한을 체크하는 오류 수정
- "너무 빠른 시간내에 게시글을 ..." 메시지 출력시 스크랩되지 않도록 수정
- #552 
- #553 
- #554 
- #556

fix: 스크랩/1:1문의/쪽지/부트스트랩 테마 오류사항 수정

---

api/settings.py

- 실제 적용되는 값은 `.env`파일에 입력해서 사용할 수 있으므로 혼동되지 않도록
- #559

docs: ApiSettings 클래스 주석 추가

---

api/v1/dependencies/current_connect.py
api/v1/models/current_connect.py
api/v1/routers/__init__.py
api/v1/routers/current_connect.py

- 현재 접속자 목록 응답에 회원 이미지 추가
- REST API 요청 시 현재 접속자 기록 추가
- #561

fix: REST API > 현재접속자 관련 수정사항 2건 작업

---

lib/dependency/dependencies.py

로그인 검증 로직에 `//` 케이스 검증 로직을 추가
- validate_login_url
- #582

fix: Open Redirect 검증 로직 우회 취약점 수정

---

api/v1/dependencies/current_connect.py
service/board_new/board_new.py

- 데이터베이스 트랜잭션 후, 미리 불러온 orm 객체와 세션 데이터를 동기화 -> orm 객체의 값이 잘못 반영 되는 오류 수정
- REST API를 통한 최신글 조회시 이미지, 첨부파일 정보를  출력할 수 있도록 추가
#585 
#579

feat, fix: REST API 이슈 관련 - 수정 및 기능 추가

---

api/v1/models/board.py
api/v1/routers/board_new.py
service/board_new/board_new.py

- view_type : 게시글/댓글 구분
- rows : 출력할 최신글 갯수
- #575

feat: REST API > 최신글 조회 요청에 Query 파라미터 추가

---

api/v1/models/board.py
api/v1/routers/board.py
service/board/list_post.py
service/board_new/board_new.py

게시글에 썸네일 정보를 포함하여 게시글 목록, 최신글 목록 API에서 조회 가능하도록 하였습니다..

[add] REST API > 게시글 썸네일 정보 추가

---

lib/mail.py
templates/basic/bbs/mail_form/qa_answered_mail.html

[fix] #618 QA 질문 알림 메일 Template 적용 / 템플릿 태그 효과 적용

---

api/v1/routers/member.py

[add] #619 REST API > 비밀번호 검증 API 추가

---

api/v1/routers/board.py
bbs/board.py
service/board/board.py
templates/basic/board/basic/write_form.html
templates/basic/board/gallery/write_form.html
templates/basic/mobile/board/basic/write_form.html
templates/basic/mobile/board/gallery/write_form.html

관리자
- 비밀번호 없이 모든 글 수정 가능하도록 변경
#625 

[fix] #625 게시글 수정시 작성자 검증 로직 수정

---

core/middleware.py
core/settings.py
example.env
lib/print_log.py

- CORS 설정을 .env 의 작성 내용을 따르도록 변경
- CORS 설정에서 allow_origins를 모든 도메인으로 할 경우, allow_credentials를 False로 설정
#626

[fix] #626 CORS 보안 설정 변경 및 환경변수화

---

api/v1/models/board.py
api/v1/routers/board.py
service/board/list_post.py

- Template: 게시글 목록 조회시 일반 게시글에서 공지글 제거
- REST API: 게시글 목록 조회시 공지글 항목 추가
- 게시글 목록 조회시 게시글 추가 정보 등록 공통부분 리팩토링
#633

[fix/add] Template: 게시판 조회시 일반 게시글에서 공지글 제거 / REST API: 게시판 조회시 공지글 별도 출력

---

bbs/register.py
lib/dependency/member.py

로그인이 되어 있는 상태에서 회원가입 페이지로 이동할 수 있는 오류 수정
#620

[fix] #620 회원가입 페이지 > 로그아웃 상태에서만 접근 허용
