bbs/board.py

세션과 함께 로그인한 유저 mb_id와 게시글의 mb_id가 일치하지 않을 때의 조건도 비교

fix: #284 본인의 게시글 읽을 시 포인트 소진하는 오류 수정

---

core/middleware.py
lib/board_lib.py
lib/common.py
templates/basic/bbs/popular.html
templates/basic/board/basic/list_post.html
templates/basic/board/gallery/list_post.html
templates/basic/faq/faq.html
templates/taeho/bbs/popular.html
templates/taeho/board/basic/list_post.html
templates/taeho/board/gallery/list_post.html
templates/taeho/faq/faq.html

- #293
- #281 수정한 내용에서 조건문 누락 추가
- #290 
- #292 
- #300 
- 인기검색어 출력 갯수 수정 (7개 -> 10개)

fix: 반응형 > 모바일 메인페이지 깨짐 문제 수정 외 4건

---

requirements.txt

- fastapi 0.109.0 버전 설치 오류 해결
```bash
ERROR: fastapi 0.109.0 has requirement starlette<0.36.0,>=0.35.0, but you'll have starlette 0.27.0 which is incompatible.
```

chore: starlette 버전이 0.27.0 이상 설치되도록 수정

---

bbs/board.py

제 개발환경에서는 오류 재현이 어려워, 해당 오류 발생 시 로그인 세션이 풀린다는 힌트(?)를 토대로 
**비회원 접근일 경우 경고문구를 추가**했습니다.
- #263

fix: #263 포인트 소진 경고창에서 비회원 경고문구 추가

---

admin/admin_visit.py
lib/common.py

sql 문법 차이로 인해 database engine에 따라 쿼리문 분기
visit 테이블 vi_date, vi_time를 조합하여 날짜비교를 하는 연산에서
SQLite: concat 문법이 사용불가하고,
PostgreSQL: 날짜 형식이 유지되어야 비교연산이 가능.
위와 같은 이유로 database 종류에 따라 orm sql문 분기하였습니다.
#362

fix. DB 호환성 오류 수정

---

admin/admin_menu_bbs.json
admin/admin_menu_shop_incomplete.json
admin/admin_menu_sms_incomplete.json
admin/templates/basic/base.html
plugin/demo_plugin/admin/admin_router.py
plugin/demo_plugin/plugin_config.py
plugin/demo_plugin/user/__init__.py
plugin/demo_todo/admin/admin_router.py
plugin/demo_todo/plugin_config.py
plugin/demo_todo/user/__init__.py

플러그인 작성시 변경사항입니다.
플러그인 url 에 / 프리픽스가 없었느데 접두사가 없는 라우터등록시 오류발생으로 인해
fastapi 라우터처럼  router 접두사에 / 를 붙이게 변경되었습니다.
plugin_config.py 
의 router_prefix, admin_router_prefix 변수 지정시 / 를 반드시 붙여야합니다.
router_prefix  예시
`router_prefix  = '/target_url' `  
플러그인 관리자의 // 중복으로 관리자 메뉴 json 의 url 에 / 추가
https://sir.kr/bbs/board.php?bo_table=g6_plugin&wr_id=1#c_15

fix: 플러그인 라우터 규칙 접두사 / 를 붙이게 변경

---

admin/templates/basic/qa_config_form.html

**Before**
어드민 페이지 - 게시판관리 - 1:1문의설정 페이지 내 `SMS설정` 링크가 `http://127.0.0.1/g5-update/adm/config_form.php#anc_cf_sms`으로 잘못 설정되어 있음
**After**
`/admin/config_form#anc_cf_sms` 링크로 수정

[fix] 관리자 1:1문의설정 내 SMS 설정 안내 링크 수정

---

lib/board_lib.py

**Before**
에디터로 첨부된 이미지의 경로는 http://127.0.0.1/data/editor/{img_name} 와 같은 웹 주소 형태이기에 썸네일 체크/생성하는 로직 내 os.path로는 체크가 불가하여 썸네일이 생성되지 않음
**After**
os.path로 체크할 수 있도록 이미지 경로를 ./data/editor/{img_name}으로 변환 
- #278

[fix] #278 에디터로 이미지 업로드 시 썸네일 노출 안되는 오류 수정

---

lib/captcha/templates/recaptcha_v2.html
lib/captcha/templates/recaptcha_v2_invisible.html
static/js/common.js
templates/basic/board/basic/read_post.html
templates/basic/board/basic/write_form.html
templates/basic/board/gallery/read_post.html
templates/basic/board/gallery/write_form.html
templates/basic/member/register_form.html
templates/basic/qa/qa_form.html

- 기존에는 `btn_submit` 버튼이 상반되는 두가지 오류를 같이 가지고있었다. 
1. 활성화 :  서버에서 오류 발생 이후 **재 등록을 못하는** 오류
2. 비활성화 : form 전송 요청이 **중복 발생**하는 오류
- 경고창 출력 이후, `histroy.back()`을 통해서 페이지에 다시 접근하기 때문에  
뒤로가기 이벤트를 체크해서 `btn_submit`버튼을 다시 활성화 하도록 처리함
- #350 
- #360 
- #353 
- Captcha Temaplate 파일에서 불필요한 스크립트 제거

fix: 폼 submit 이후 버튼 활성화/비활성화 오류 수정

---

admin/admin_point.py

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
합계 포인트 없을 때 None 이 반환되어 500 에러 접속 불가
/admin/point_list

fix: 관리자 > 포인트관리 합계포인트 없을때 접속오류

---

lib/board_lib.py

- 이미지 파일에 추가적인 querystring이 붙어있어 생성하지 못하는 것으로 확인됨
- 이후 정확한 파일 확장자를 추출할 수 있도록 코드 개선 필요

[fix] 섬네일 생성하지 못하는 이미지 예외처리 추가

---

admin/admin_theme.py
core/exception.py
core/template.py
lib/template_functions.py

테마를 변경하면서 `TEMPLATES_DIR` 전역변수를 갱신하지 못해서 발생한 오류
현재 테마 경로를 `TemplateService` 클래스에서 관리 할 수 있도록 변경
- `TEMPLATES_DIR` -> `_templates_dir` 
테마를 변경하면서 경로 재 설정 시, 0번 인덱스만 제거 후 갱신하면서 발생
- 모바일 환경에서 접근 할 경우, PC, 모바일 둘 다 갱신해야한다.
1. 이전 테마 경로를 제거 후 새로운 테마 경로를 추가하도록 수정
예) `['templates/basic/mobile', 'templates/basic', 'templates/basic', 'lib/editor/templates', 'lib/captcha/templates', 'plugin']`  에서 templates/basic로 시작되는 경로 제거
2. _templates_dir를 갱신하도록 수정
[godglee 님 제보](https://sir.kr/qa/524242)

fix: 테마 변경 시 오류사항 수정

---

admin/admin_visit.py
admin/templates/basic/visit_forms.html

1. visit_forms.html이 import 여서 함수를 제외한 상위 템플릿의 context 가 전달되지 않아
날짜 input 태그에 fr_date, to_date 가 표시 되지 않았습니다.  
-> url 쿼리스트링에서 가져오도록 수정
2. 접속자 , 시간
Visit.vi_time 을 hour 이름으로 가져와서 Visit.vi_time 은 따로 필요없습니다.
3. 요일 탭 쿼리 group by 시 필요한 컬럼 추가
데이터베이스 별로 요일(day of week)을 출력하는 기준이 다르기 때문에
계산을 위해 vi_date 가 필요

fix: 관리자 접속자 시간, 요일 탭 오류 수정

---

lib/board_lib.py

로그인 상태에서 작성가능한 게시판에서 로그인 해제후 글 작성시
글쓴이 정보가 누락되는 오류 수정
세션 종료 등, 비정상적인 경로로 작성시 예외처리
#388

[fix] #388 게시글 작성시 작성자 정보 누락되는 오류 수정

---

admin/templates/basic/base.html

플러그인 매뉴는 menu_order css 를 주요메뉴 1~3  지나고 4부터 시작하게 수정합니다.
#418

fix: #418 plugin 메뉴 menu_order 를 4번 부터로 변경

---

bbs/board.py
bbs/qa.py
core/middleware.py
lib/html_sanitizer/__init__.py
lib/html_sanitizer/allowed_dict.py
lib/html_sanitizer/html_sanitizer.py
requirements.txt
templates/basic/qa/qa_view.html

1) HTTP response - Content Security Policy를 활용
미들웨어의 response header에 src를 통해 불러오는 외부 data에 제한을 둡니다
2) lxml 라이브러리 기반의 html sanitizer 적용
bleach, nh3, html-sanitizer, DomPurify 등 다양한 라이브러리를 검토
```
bleach - 가장 범용적이나 2023년 1월부터 deprecated 상태
nh3 - bleach에 대안으로도 많이 이용되나, 라이브러리의 많은 부분이 Rust로 쓰여있어 디버깅에 어려움이 있을것으로 예상됨
html-sanitizer - lxml을 dependency로 두고있음, lxml을 직접 사용하며 용도에 맞게 변형하며 사용하는 것이 용이
DomPurify - 3년 전부터 커밋이 올라오지 않아서 지속적인 관리가 되고 있지 않은 것으로 판단
```
위의 특성들을 고려하여, 범용성, 성능, 라이브러리 유지보수 가능성 측면에서 lxml을 적합할 것으로 판단하고 작업했습니다.
**Allowlist(Whitelist) vs Blocklist(Blacklist)**
lxml 라이브러리는 allowlist, blocklist 두 가지 측면에서 모두 접근이 가능한데,
allow_tags, safe_attrs를 통해서 allowlist 방식으로 XSS에 대응하도록 했습니다.
**style 관련**
개별 html …

feat. Stored XSS 방지 기능 추가 #314, #387, #390

---

core/formclass.py

- 사용자페이지에서 html태그를 추가하는 것만으로도 여분필드를 사용할 수 있도록 수정
-  formclass.py > 게시판, Q&A의 여분필드 속성 값 추가
- #460
- https://sir.kr/qa/525894

fix: 사용자페이지에서 게시판, Q&A 여분필드가 입력되지 않는 오류 수정

---

core/database.py

매번 설정이 불러와지는 문제점 수정 - > DBSetting 클래스도 싱글턴 적용
load_dotenv 삭제 바로 아랫줄  dotenv_values 함수가 env 파일을 호출해서 불필요
단일요청 응답시간은 줄었으나 동시접속자 증가시 문제는 여전합니다.
---
설치확인

fix: DBSetting 싱글턴 적용

---

lib/board_lib.py

비밀번호 확인 페이지로 이동할 때 토큰이 Query String에 추가되기 때문에 토큰 중복 오류가 발생함.
- Query String에 `token` 파라미터가 중복으로 추가되지 않도록 처리
오류 제보
https://sir.kr/qa/527109

fix: 비회원 글 삭제 시 토큰 오류 수정

---

lib/social/providers/kakao.py
lib/social/social.py

* 카카오 client_secret 키 설정시 오류 수정 - 카카오 콘솔에서 시크릿키 활성화시 Bad Client Credentials 오류 발생
* 서버 재시작 할 때 카카오 모듈 로딩 오류 수정

fix: 카카오 로그인 client_secret 키 설정시 오류 수정

---

lib/board_lib.py

기본 제공되는 게시판 설정(`free`, `notice` 등..)이 `g6_board` 테이블에 없을 경우
`render_latest_posts()`에서 발생하는 오류 해결
[Internal Server Error (최신 게시글 조회 함수)](https://sir.kr/qa/527734)

fix: render_latest_posts() 함수 오류 수정

---

bbs/board.py

관리자 화면에서 '게시물 아래에 누구로 부터 복사, 이동됨 표시' 옵션을 해제한 상태로 게시물 복사/이동시 log_msg 변수가 초기화되어 있지 않아서 다음과 같은 오류 발생하여 빈 문자열로 초기화 코드 추가
target_write.wr_content = origin_write.wr_content + log_msg
^^^^^^^
UnboundLocalError: cannot access local variable 'log_msg' where it is not associated with a value

게시물 이동 코멘트 변수 초기화

---

bbs/login.py
lib/dependency/dependencies.py

- Redirect URL을 검증하는 의존성 주입 함수 추가
- `validate_login_url`
- #557

fix: 로그인 시 Open Redirect 취약점 수정

---

core/database.py
core/models.py
install/router.py

- 설치 시 이미 선언/할당된 메타데이터의 테이블 이름을 갱신하도록 코드 추가
``` python
tables = Base.metadata.tables.values()
for table in tables:
new_table_name = table.name.replace("g6_", form_data.db_table_prefix)
table.name = new_table_name
Base.metadata.create_all(bind=engine)
```
- `core/models.py`, `install/router.py` 코드스타일 일부 수정
- #558

fix: 그누보드6 설치 DB_TABLE_PREFIX 미적용 오류 수정

---

api/v1/auth/jwt.py
api/v1/dependencies/current_connect.py
api/v1/models/auth.py
api/v1/models/member.py
api/v1/routers/member.py
service/qa_service.py
templates/basic/member/id_find_result.html
templates/basic/member/password_find_form.html
templates/bootstrap/member/id_find_result.html
templates/bootstrap/member/password_find_form.html

- #543에서 JWT 라이브러리 변경으로 인한 오류
- 의존성 주입이 아닌 직접 회원정보를 조회
- 답변이 없는 문의글의 상세페이지에 들어갈 수 없는 오류 수정
- 답변 작성 시 답변상태가 바뀌지 않는 오류 수정
- 불필요한 권한체크 삭제
- `Member().mb_id` -> `Member.mb_id`
- #580 
- #571

fix: 오류사항 6건 수정

---

lib/dependency/dependencies.py

`validate_login_url()` 함수의 조건문이 정상적인 요청의 url 변수도 예외처리 하는 오류
- `validate_login_url()` 함수의 URL 유효성 검사 조건문 수정
- `validate_login_url()` > `allow_urls` 리스트 삭제

fix: 로그인 시, '올바르지 않은 URL입니다.' 오류 수정

---

templates/bootstrap/board/basic/write_form.html
templates/bootstrap/board/gallery/write_form.html

부트스트랩 테마의 게시글 작성 템플릿에서 작성/수정 여부에 따라서 붙어야 하는 wr_id 조건식을 추가하였습니다.
#595

[fix] #595 부트스트랩 > 게시글 작성 폼 - 생성/수정 URL 조건 누락 수정

---

api/settings.py
api/v1/auth/jwt.py
api/v1/dependencies/member.py
api/v1/models/__init__.py
api/v1/models/auth.py
api/v1/models/member.py
api/v1/models/response.py
api/v1/routers/__init__.py
api/v1/routers/auth.py
api/v1/routers/captcha.py
api/v1/routers/member.py
bbs/register.py
core/exception.py
core/formclass.py
lib/common.py
lib/dependency/dependencies.py
lib/dependency/member.py
lib/mail.py
service/member_service.py
static/js/jquery.register_form.js
templates/basic/member/certify_email_update_form.html
templates/basic/member/member_profile.html
templates/basic/member/register_form.html
templates/bootstrap/member/member_profile.html
templates/bootstrap/member/register_form.html

1. Captcha 검증기능 추가
2. JWT
- Refresh Token의 sub claim에 사용자 ID를 추가
- JWT 생성 시, nbf(활성화 시간), aud(대상자) 속성 추가
- timestamp > float -> int형 변경
1. 금지단어, 욕설 필터링 추가
2. 비밀번호 자릿수 제한 오류 수정
3. 가입정보 유효성 검사 추가 (추천인 포함)
4. 여분필드 조회/수정 추가
5. 인증메일 변경 기능 추가 (템플릿, API)
1. 로그인 시, '올바르지 않은 URL입니다.' 오류 재수정
- 잘못된 URL이더라도 로그인 될 수 있도록 수정
- 경고창 출력(예외처리) -> 메인 페이지로 리다이렉트
2. 자기소개 > 삭제된 css를 불러오는 코드 삭제
- #592 
- #594 
- #598

fix, feat: 회원가입 및 REST API 이슈 및 오류사항 수정

---

api/v1/routers/memo.py
bbs/memo.py
lib/mail.py
service/board/board.py
service/memo_service.py
service/point_service.py
templates/basic/bbs/mail_form/qa_answered_mail.html

- REST API를 통한 파일 업로드 요청의 경우 None 값이 포함되는 경우 None 에서 filename을 찾는 오류 발생
-> 파일이 존재하는 경우만 검증로직을 수행하도록 수정
- 쪽지 전송 포인트 중복 차감 에러 수정, 문구 변경
- 특정 회원 지정 쪽지 전송시, input 창에 유저 정보가 입력되도록 UX개선
- QA 답변 알람 메일 템플릿 적용
#609
#610

[fix] 파일 업로드 에러 / 쪽지 전송 에러 및 UX 개선 / QA 메일 템플릿 적용

---

api/v1/models/board.py
api/v1/routers/board.py

- 댓글 생성 REST API에 대한 documentation 설명 중, request body에 포함되지 않는 wr_id에 대한 설명을 삭제했습니다.
- 댓글 정보를 불러오는 대댓글 표시를 위해 API response에 wr_comment_reply 키를 추가했습니다.

[fix] REST API > 댓글 관련 오류 수정 / 누락된 기능 추가

---

api/v1/models/board.py
api/v1/routers/board.py
service/board/board.py

REST API 게시판 조회시 게시글 페이지당 출력의 목록수(per_page )를 0으로 할 시에,
개별 게시판 또는 전체 게시판 출력 목록수 설정값을 따르도록 설정
#617 

[fix] #617 REST API > 게시판 조회 - 게시글 페이지당 목록수 수정

---

service/ajax/ajax.py

- response json Key 오류 수정
- as_uid 값만으로 row 탐색 후 mb_id 검증
#622

[fix] 자동저장글 호출/저장시 타인 글에 대한 접근 오류 수정

---

api/v1/models/board.py
api/v1/routers/board_new.py
service/board_new/board_new.py

- Response Model 적용 출력 json key 제한 (#624 wr_password 제거)
- 개별글 정보: 게시판 목록과 같은 양식으로 출력
- mb_image, mb_icon, good, nogood 정보 출력
#624

[fix] #624 REST API > 최근 게시물 목록 출력 양식 수정
